steps:
  # Build the React application
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to Firebase Hosting
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']

options:
  logging: CLOUD_LOGGING_ONLY
